/*
 * move.mil Prime API
 * The API for move.mil Prime actions.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Entitlements
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-10-10T14:01:49.800Z")
public class Entitlements {
  @SerializedName("totalWeightSelf")
  private Integer totalWeightSelf = null;

  @SerializedName("dependentsAuthorized")
  private Boolean dependentsAuthorized = null;

  @SerializedName("totalDependents")
  private Integer totalDependents = null;

  @SerializedName("proGearWeight")
  private Integer proGearWeight = null;

  @SerializedName("proGearWeightSpouse")
  private Integer proGearWeightSpouse = null;

  @SerializedName("nonTemporaryStorage")
  private Boolean nonTemporaryStorage = null;

  @SerializedName("privatelyOwnedVehicle")
  private Boolean privatelyOwnedVehicle = null;

  @SerializedName("storageInTransit")
  private Integer storageInTransit = null;

  public Entitlements totalWeightSelf(Integer totalWeightSelf) {
    this.totalWeightSelf = totalWeightSelf;
    return this;
  }

   /**
   * Get totalWeightSelf
   * @return totalWeightSelf
  **/
  @ApiModelProperty(example = "18000", value = "")
  public Integer getTotalWeightSelf() {
    return totalWeightSelf;
  }

  public void setTotalWeightSelf(Integer totalWeightSelf) {
    this.totalWeightSelf = totalWeightSelf;
  }

  public Entitlements dependentsAuthorized(Boolean dependentsAuthorized) {
    this.dependentsAuthorized = dependentsAuthorized;
    return this;
  }

   /**
   * Get dependentsAuthorized
   * @return dependentsAuthorized
  **/
  @ApiModelProperty(example = "true", value = "")
  public Boolean isDependentsAuthorized() {
    return dependentsAuthorized;
  }

  public void setDependentsAuthorized(Boolean dependentsAuthorized) {
    this.dependentsAuthorized = dependentsAuthorized;
  }

  public Entitlements totalDependents(Integer totalDependents) {
    this.totalDependents = totalDependents;
    return this;
  }

   /**
   * Get totalDependents
   * @return totalDependents
  **/
  @ApiModelProperty(example = "2", value = "")
  public Integer getTotalDependents() {
    return totalDependents;
  }

  public void setTotalDependents(Integer totalDependents) {
    this.totalDependents = totalDependents;
  }

  public Entitlements proGearWeight(Integer proGearWeight) {
    this.proGearWeight = proGearWeight;
    return this;
  }

   /**
   * Get proGearWeight
   * @return proGearWeight
  **/
  @ApiModelProperty(example = "2000", value = "")
  public Integer getProGearWeight() {
    return proGearWeight;
  }

  public void setProGearWeight(Integer proGearWeight) {
    this.proGearWeight = proGearWeight;
  }

  public Entitlements proGearWeightSpouse(Integer proGearWeightSpouse) {
    this.proGearWeightSpouse = proGearWeightSpouse;
    return this;
  }

   /**
   * Get proGearWeightSpouse
   * @return proGearWeightSpouse
  **/
  @ApiModelProperty(example = "500", value = "")
  public Integer getProGearWeightSpouse() {
    return proGearWeightSpouse;
  }

  public void setProGearWeightSpouse(Integer proGearWeightSpouse) {
    this.proGearWeightSpouse = proGearWeightSpouse;
  }

  public Entitlements nonTemporaryStorage(Boolean nonTemporaryStorage) {
    this.nonTemporaryStorage = nonTemporaryStorage;
    return this;
  }

   /**
   * Get nonTemporaryStorage
   * @return nonTemporaryStorage
  **/
  @ApiModelProperty(example = "false", value = "")
  public Boolean isNonTemporaryStorage() {
    return nonTemporaryStorage;
  }

  public void setNonTemporaryStorage(Boolean nonTemporaryStorage) {
    this.nonTemporaryStorage = nonTemporaryStorage;
  }

  public Entitlements privatelyOwnedVehicle(Boolean privatelyOwnedVehicle) {
    this.privatelyOwnedVehicle = privatelyOwnedVehicle;
    return this;
  }

   /**
   * Get privatelyOwnedVehicle
   * @return privatelyOwnedVehicle
  **/
  @ApiModelProperty(example = "false", value = "")
  public Boolean isPrivatelyOwnedVehicle() {
    return privatelyOwnedVehicle;
  }

  public void setPrivatelyOwnedVehicle(Boolean privatelyOwnedVehicle) {
    this.privatelyOwnedVehicle = privatelyOwnedVehicle;
  }

  public Entitlements storageInTransit(Integer storageInTransit) {
    this.storageInTransit = storageInTransit;
    return this;
  }

   /**
   * Get storageInTransit
   * @return storageInTransit
  **/
  @ApiModelProperty(example = "90", value = "")
  public Integer getStorageInTransit() {
    return storageInTransit;
  }

  public void setStorageInTransit(Integer storageInTransit) {
    this.storageInTransit = storageInTransit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Entitlements entitlements = (Entitlements) o;
    return Objects.equals(this.totalWeightSelf, entitlements.totalWeightSelf) &&
        Objects.equals(this.dependentsAuthorized, entitlements.dependentsAuthorized) &&
        Objects.equals(this.totalDependents, entitlements.totalDependents) &&
        Objects.equals(this.proGearWeight, entitlements.proGearWeight) &&
        Objects.equals(this.proGearWeightSpouse, entitlements.proGearWeightSpouse) &&
        Objects.equals(this.nonTemporaryStorage, entitlements.nonTemporaryStorage) &&
        Objects.equals(this.privatelyOwnedVehicle, entitlements.privatelyOwnedVehicle) &&
        Objects.equals(this.storageInTransit, entitlements.storageInTransit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalWeightSelf, dependentsAuthorized, totalDependents, proGearWeight, proGearWeightSpouse, nonTemporaryStorage, privatelyOwnedVehicle, storageInTransit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Entitlements {\n");
    
    sb.append("    totalWeightSelf: ").append(toIndentedString(totalWeightSelf)).append("\n");
    sb.append("    dependentsAuthorized: ").append(toIndentedString(dependentsAuthorized)).append("\n");
    sb.append("    totalDependents: ").append(toIndentedString(totalDependents)).append("\n");
    sb.append("    proGearWeight: ").append(toIndentedString(proGearWeight)).append("\n");
    sb.append("    proGearWeightSpouse: ").append(toIndentedString(proGearWeightSpouse)).append("\n");
    sb.append("    nonTemporaryStorage: ").append(toIndentedString(nonTemporaryStorage)).append("\n");
    sb.append("    privatelyOwnedVehicle: ").append(toIndentedString(privatelyOwnedVehicle)).append("\n");
    sb.append("    storageInTransit: ").append(toIndentedString(storageInTransit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

