swagger: '2.0'
info:
  description: The API for move.mil Prime actions.
  version: 0.1.0
  title: move.mil Prime API
  license:
    name: MIT
    url: https://github.com/transcom/mymove/blob/master/LICENSE.md
basePath: /api/v1
consumes:
  - application/json
produces:
  - application/json
definitions:
  MoveTaskOrder:
    type: object
    properties:
      id:
        type: string
        format: uuid
        example: 1f2270c7-7166-40ae-981e-b200ebdf3054
      code:
        type: string
        example: USMC-0001
      moveID:
        type: string
        format: uuid
        example: c56a4180-65aa-42ec-a945-5fd21dec0538
      moveDate:
        type: string
        format: date
      status:
        type: string
        enum:
          - APPROVED
          - REJECTED
          - SUBMITTED
      entitlements:
        $ref: '#/definitions/Entitlements'
      moveTaskOrdersType:
        type: string
        enum:
          - NON_TEMPORARY_STORAGE
          - PRIME
      customer:
        $ref: '#/definitions/Customer'
      requestedPickupDate:
        type: string
        format: date
      originDutyStation:
        type: string
        format: uuid
        example: 1f2270c7-7166-40ae-981e-b200ebdf3054
      originPPSO:
        type: string
        format: uuid
        example: 1f2270c7-7166-40ae-981e-b200ebdf3054
      destinationDutyStation:
        type: string
        format: uuid
        example: 1f2270c7-7166-40ae-981e-b200ebdf3054
      destinationPPSO:
        type: string
        format: uuid
        example: 1f2270c7-7166-40ae-981e-b200ebdf3054
      remarks:
        type: string
        example: Requires more gentle care
      serviceItems:
        type: array
        items:
          $ref: '#/definitions/ServiceItem'
      createdAt:
        type: string
        format: date
      updatedAt:
        type: string
        format: date
      deletedAt:
        type: string
        format: date
  MoveTaskOrders:
    type: array
    items:
      $ref: '#/definitions/MoveTaskOrder'
  ServiceItem:
    type: object
    properties:
      id:
        type: string
        format: uuid
        example: 1f2270c7-7166-40ae-981e-b200ebdf3054
      MoveTaskOrderID:
        type: string
        format: uuid
        example: 1f2270c7-7166-40ae-981e-b200ebdf3054
      status:
        type: string
        enum:
          - APPROVED
          - SUBMITTED
          - REJECTED
      feeType:
        type: string
        enum:
          - COUNSELING
          - CRATING
          - TRUCKING
          - SHUTTLE
      total:
        type: integer
        format: cents
      quantity:
        type: integer
      rate:
        type: integer
      description:
        type: string
      submittedAt:
        type: string
        format: date
      approvedAt:
        type: string
        format: date
      rejectedAt:
        type: string
        format: date
      createdAt:
        type: string
        format: date
      updatedAt:
        type: string
        format: date
      deletedAt:
        type: string
        format: date
  Entitlements:
    type: object
    properties:
      totalWeightSelf:
        type: integer
        example: 18000
      dependentsAuthorized:
        type: boolean
        example: true
      totalDependents:
        type: integer
        example: 2
      proGearWeight:
        type: integer
        example: 2000
      proGearWeightSpouse:
        type: integer
        example: 500
      nonTemporaryStorage:
        type: boolean
        example: false
      privatelyOwnedVehicle:
        type: boolean
        example: false
      storageInTransit:
        type: integer
        example: 90
  Customer:
    type: object
  ClientError:
    type: object
    properties:
      title:
        type: string
      detail:
        type: string
    required:
      - title
      - detail
  ValidationError:
    allOf:
      - $ref: '#/definitions/ClientError'
      - type: object
    properties:
      invalid_fields:
        type: object
        additionalProperties:
          type: string
    required:
      - invalid_fields
paths:
  /move_task_orders:
    get:
      summary: List all move task rders
      description: Returns a list of move task orders
      operationId: indexMoveTaskOrders
      tags:
        - MoveTaskOrder
      parameters:
        - in: query
          name: requestor
          type: string
          description: Unique identifier of the user making the request
          required: true
        - in: query
          name: filter
          type: array
          items:
            type: string
        - in: query
          name: page
          type: integer
        - in: query
          name: perPage
          type: integer
      responses:
        200:
          description: success
          headers:
            Content-Range:
              type: string
              description: Used for pagination
          schema:
            $ref: '#/definitions/MoveTaskOrders'
        400:
          description: invalid request
          schema:
            $ref: '#/definitions/ClientError'
        422:
          description: validation error
          schema:
            $ref: '#/definitions/ValidationError'
        401:
          description: request requires user authentication
          schema:
            $ref: '#/definitions/ClientError'
        404:
          description: not found
          schema:
            $ref: '#/definitions/ClientError'
        500:
          description: server error
  /move_task_orders/{move_task_order_id}/service_items:
    post:
      summary: Creates a service item for a move order by id
      description: Creates a service item for a move order by id
      operationId: createServiceItem
      tags:
        - MoveTaskOrder
      parameters:
        - in: body
          name: service_item
          description: Unique identifier of the user making the request
          schema:
            type: object
            required:
              - requestor
            properties:
              requestor:
                type: string
        - in: path
          name: move_task_order_id
          type: string
          format: uuid
          required: true
        - in: query
          name: filter
          type: array
          items:
            type: string
        - in: query
          name: page
          type: integer
        - in: query
          name: perPage
          type: integer
      responses:
        200:
          description: success
          headers:
            Content-Range:
              type: string
              description: Used for pagination
          schema:
            $ref: '#/definitions/ServiceItem'
        400:
          description: invalid request
          schema:
            $ref: '#/definitions/ClientError'
        422:
          description: validation error
          schema:
            $ref: '#/definitions/ValidationError'
        401:
          description: request requires user authentication
          schema:
            $ref: '#/definitions/ClientError'
        404:
          description: not found
          schema:
            $ref: '#/definitions/ClientError'
        500:
          description: server error
  /move_task_orders/{move_task_order_id}/complete_counseling:
    post:
      summary: Completes counseling for a move task order by id
      description: Completes counseling for a move task order by id
      operationId: completeCounseling
      tags:
        - MoveTaskOrder
      parameters:
        - in: path
          name: move_task_order_id
          type: string
          format: uuid
          required: true
        - in: body
          name: options
          schema:
            type: object
            required:
              - requestor
            properties:
              requestor:
                type: string
              isPPM:
                type: boolean
              hasExcess:
                type: boolean
      responses:
        200:
          description: success
          schema:
            $ref: '#/definitions/MoveTaskOrder'
        400:
          description: invalid request
          schema:
            $ref: '#/definitions/ClientError'
        422:
          description: validation error
          schema:
            $ref: '#/definitions/ValidationError'
        401:
          description: request requires user authentication
          schema:
            $ref: '#/definitions/ClientError'
        404:
          description: not found
          schema:
            $ref: '#/definitions/ClientError'
        500:
          description: server error
          

