=begin
#move.mil API

#The Prime API for move.mil

OpenAPI spec version: 0.0.1
Contact: dp3@truss.works
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/address'
require 'swagger_client/models/body'
require 'swagger_client/models/client_error'
require 'swagger_client/models/create_payment_request_payload'
require 'swagger_client/models/customer'
require 'swagger_client/models/customer_contact_type'
require 'swagger_client/models/dimension_type'
require 'swagger_client/models/duty_station'
require 'swagger_client/models/entitlements'
require 'swagger_client/models/error'
require 'swagger_client/models/mto_agent'
require 'swagger_client/models/mto_agent_type'
require 'swagger_client/models/mto_agents'
require 'swagger_client/models/mto_service_item'
require 'swagger_client/models/mto_service_item_basic'
require 'swagger_client/models/mto_service_item_ddfsit'
require 'swagger_client/models/mto_service_item_dofsit'
require 'swagger_client/models/mto_service_item_dimension'
require 'swagger_client/models/mto_service_item_domestic_crating'
require 'swagger_client/models/mto_service_item_model_type'
require 'swagger_client/models/mto_service_item_shuttle'
require 'swagger_client/models/mto_service_item_status'
require 'swagger_client/models/mto_shipment'
require 'swagger_client/models/mto_shipment_type'
require 'swagger_client/models/mto_shipments'
require 'swagger_client/models/move_order'
require 'swagger_client/models/move_task_order'
require 'swagger_client/models/move_task_orders'
require 'swagger_client/models/payment_request'
require 'swagger_client/models/payment_request_status'
require 'swagger_client/models/payment_requests'
require 'swagger_client/models/proof_of_service_docs'
require 'swagger_client/models/re_service_code'
require 'swagger_client/models/service_item'
require 'swagger_client/models/service_item_params'
require 'swagger_client/models/update_payment_request_status'
require 'swagger_client/models/upload'
require 'swagger_client/models/validation_error'

# APIs
require 'swagger_client/api/move_task_order_api'
require 'swagger_client/api/mto_service_item_api'
require 'swagger_client/api/mto_shipment_api'
require 'swagger_client/api/payment_requests_api'
require 'swagger_client/api/uploads_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
