/*
 * move.mil API
 * The Prime API for move.mil
 *
 * OpenAPI spec version: 0.0.1
 * Contact: dp3@truss.works
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.MTOServiceItem;
import io.swagger.client.model.MTOServiceItemModelType;
import io.swagger.client.model.MTOServiceItemStatus;
import io.swagger.client.model.ReServiceCode;
import java.io.IOException;
import java.util.UUID;

/**
 * Describes a basic service item subtype of a MTOServiceItem.
 */
@ApiModel(description = "Describes a basic service item subtype of a MTOServiceItem.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-06T14:55:33.605Z")
public class MTOServiceItemBasic extends MTOServiceItem {
  @SerializedName("reServiceCode")
  private ReServiceCode reServiceCode = null;

  public MTOServiceItemBasic reServiceCode(ReServiceCode reServiceCode) {
    this.reServiceCode = reServiceCode;
    return this;
  }

   /**
   * Get reServiceCode
   * @return reServiceCode
  **/
  @ApiModelProperty(required = true, value = "")
  public ReServiceCode getReServiceCode() {
    return reServiceCode;
  }

  public void setReServiceCode(ReServiceCode reServiceCode) {
    this.reServiceCode = reServiceCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MTOServiceItemBasic mtOServiceItemBasic = (MTOServiceItemBasic) o;
    return Objects.equals(this.reServiceCode, mtOServiceItemBasic.reServiceCode) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reServiceCode, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MTOServiceItemBasic {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    reServiceCode: ").append(toIndentedString(reServiceCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

