/*
 * Milmove Prime API
 * The Prime API is a RESTful API that enables the Prime contractor to request information about upcoming moves, update the details and status of those moves, and make payment requests. It uses Mutual TLS for authentication procedures.  All endpoints are located at `primelocal/prime/v1/`. 
 *
 * OpenAPI spec version: 0.0.1
 * Contact: dp3@truss.works
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.MTOServiceItemModelType;
import io.swagger.client.model.MTOServiceItemStatus;
import java.io.IOException;
import java.util.UUID;

/**
 * MTOServiceItem describes a base type of a service item. Polymorphic type. Both Move Task Orders and MTO Shipments will have MTO Service Items.
 */
@ApiModel(description = "MTOServiceItem describes a base type of a service item. Polymorphic type. Both Move Task Orders and MTO Shipments will have MTO Service Items.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-14T14:53:44.624-07:00")

public class MTOServiceItem {
  @SerializedName("id")
  private UUID id = null;

  @SerializedName("moveTaskOrderID")
  private UUID moveTaskOrderID = null;

  @SerializedName("mtoShipmentID")
  private UUID mtoShipmentID = null;

  @SerializedName("reServiceID")
  private UUID reServiceID = null;

  @SerializedName("reServiceName")
  private String reServiceName = null;

  @SerializedName("status")
  private MTOServiceItemStatus status = null;

  @SerializedName("rejectionReason")
  private String rejectionReason = null;

  @SerializedName("modelType")
  private MTOServiceItemModelType modelType = null;

  @SerializedName("eTag")
  private String eTag = null;

  public MTOServiceItem id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "1f2270c7-7166-40ae-981e-b200ebdf3054", value = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public MTOServiceItem moveTaskOrderID(UUID moveTaskOrderID) {
    this.moveTaskOrderID = moveTaskOrderID;
    return this;
  }

   /**
   * Get moveTaskOrderID
   * @return moveTaskOrderID
  **/
  @ApiModelProperty(example = "1f2270c7-7166-40ae-981e-b200ebdf3054", value = "")
  public UUID getMoveTaskOrderID() {
    return moveTaskOrderID;
  }

  public void setMoveTaskOrderID(UUID moveTaskOrderID) {
    this.moveTaskOrderID = moveTaskOrderID;
  }

  public MTOServiceItem mtoShipmentID(UUID mtoShipmentID) {
    this.mtoShipmentID = mtoShipmentID;
    return this;
  }

   /**
   * Get mtoShipmentID
   * @return mtoShipmentID
  **/
  @ApiModelProperty(example = "1f2270c7-7166-40ae-981e-b200ebdf3054", value = "")
  public UUID getMtoShipmentID() {
    return mtoShipmentID;
  }

  public void setMtoShipmentID(UUID mtoShipmentID) {
    this.mtoShipmentID = mtoShipmentID;
  }

  public MTOServiceItem reServiceID(UUID reServiceID) {
    this.reServiceID = reServiceID;
    return this;
  }

   /**
   * Get reServiceID
   * @return reServiceID
  **/
  @ApiModelProperty(example = "1f2270c7-7166-40ae-981e-b200ebdf3054", value = "")
  public UUID getReServiceID() {
    return reServiceID;
  }

  public void setReServiceID(UUID reServiceID) {
    this.reServiceID = reServiceID;
  }

  public MTOServiceItem reServiceName(String reServiceName) {
    this.reServiceName = reServiceName;
    return this;
  }

   /**
   * Get reServiceName
   * @return reServiceName
  **/
  @ApiModelProperty(value = "")
  public String getReServiceName() {
    return reServiceName;
  }

  public void setReServiceName(String reServiceName) {
    this.reServiceName = reServiceName;
  }

  public MTOServiceItem status(MTOServiceItemStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public MTOServiceItemStatus getStatus() {
    return status;
  }

  public void setStatus(MTOServiceItemStatus status) {
    this.status = status;
  }

  public MTOServiceItem rejectionReason(String rejectionReason) {
    this.rejectionReason = rejectionReason;
    return this;
  }

   /**
   * Get rejectionReason
   * @return rejectionReason
  **/
  @ApiModelProperty(example = "item was too heavy", value = "")
  public String getRejectionReason() {
    return rejectionReason;
  }

  public void setRejectionReason(String rejectionReason) {
    this.rejectionReason = rejectionReason;
  }

  public MTOServiceItem modelType(MTOServiceItemModelType modelType) {
    this.modelType = modelType;
    return this;
  }

   /**
   * Get modelType
   * @return modelType
  **/
  @ApiModelProperty(required = true, value = "")
  public MTOServiceItemModelType getModelType() {
    return modelType;
  }

  public void setModelType(MTOServiceItemModelType modelType) {
    this.modelType = modelType;
  }

  public MTOServiceItem eTag(String eTag) {
    this.eTag = eTag;
    return this;
  }

   /**
   * Get eTag
   * @return eTag
  **/
  @ApiModelProperty(value = "")
  public String getETag() {
    return eTag;
  }

  public void setETag(String eTag) {
    this.eTag = eTag;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MTOServiceItem mtOServiceItem = (MTOServiceItem) o;
    return Objects.equals(this.id, mtOServiceItem.id) &&
        Objects.equals(this.moveTaskOrderID, mtOServiceItem.moveTaskOrderID) &&
        Objects.equals(this.mtoShipmentID, mtOServiceItem.mtoShipmentID) &&
        Objects.equals(this.reServiceID, mtOServiceItem.reServiceID) &&
        Objects.equals(this.reServiceName, mtOServiceItem.reServiceName) &&
        Objects.equals(this.status, mtOServiceItem.status) &&
        Objects.equals(this.rejectionReason, mtOServiceItem.rejectionReason) &&
        Objects.equals(this.modelType, mtOServiceItem.modelType) &&
        Objects.equals(this.eTag, mtOServiceItem.eTag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, moveTaskOrderID, mtoShipmentID, reServiceID, reServiceName, status, rejectionReason, modelType, eTag);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MTOServiceItem {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    moveTaskOrderID: ").append(toIndentedString(moveTaskOrderID)).append("\n");
    sb.append("    mtoShipmentID: ").append(toIndentedString(mtoShipmentID)).append("\n");
    sb.append("    reServiceID: ").append(toIndentedString(reServiceID)).append("\n");
    sb.append("    reServiceName: ").append(toIndentedString(reServiceName)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    rejectionReason: ").append(toIndentedString(rejectionReason)).append("\n");
    sb.append("    modelType: ").append(toIndentedString(modelType)).append("\n");
    sb.append("    eTag: ").append(toIndentedString(eTag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

