/*
 * Milmove Prime API
 * The Prime API is a RESTful API that enables the Prime contractor to request information about upcoming moves, update the details and status of those moves, and make payment requests. It uses Mutual TLS for authentication procedures.  All endpoints are located at `primelocal/prime/v1/`. 
 *
 * OpenAPI spec version: 0.0.1
 * Contact: dp3@truss.works
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CustomerContactType;
import io.swagger.client.model.MTOServiceItem;
import io.swagger.client.model.MTOServiceItemModelType;
import io.swagger.client.model.MTOServiceItemStatus;
import io.swagger.client.model.ReServiceCode;
import java.io.IOException;
import java.util.UUID;
import org.threeten.bp.LocalDate;

/**
 * Describes a domestic destination 1st day SIT service item subtype of a MTOServiceItem.
 */
@ApiModel(description = "Describes a domestic destination 1st day SIT service item subtype of a MTOServiceItem.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-14T14:53:44.624-07:00")
public class MTOServiceItemDDFSIT extends MTOServiceItem {
  @SerializedName("reServiceCode")
  private ReServiceCode reServiceCode = null;

  @SerializedName("type")
  private CustomerContactType type = null;

  @SerializedName("timeMilitary1")
  private String timeMilitary1 = null;

  @SerializedName("firstAvailableDeliveryDate1")
  private LocalDate firstAvailableDeliveryDate1 = null;

  @SerializedName("timeMilitary2")
  private String timeMilitary2 = null;

  @SerializedName("firstAvailableDeliveryDate2")
  private LocalDate firstAvailableDeliveryDate2 = null;

  public MTOServiceItemDDFSIT reServiceCode(ReServiceCode reServiceCode) {
    this.reServiceCode = reServiceCode;
    return this;
  }

   /**
   * Get reServiceCode
   * @return reServiceCode
  **/
  @ApiModelProperty(value = "")
  public ReServiceCode getReServiceCode() {
    return reServiceCode;
  }

  public void setReServiceCode(ReServiceCode reServiceCode) {
    this.reServiceCode = reServiceCode;
  }

  public MTOServiceItemDDFSIT type(CustomerContactType type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public CustomerContactType getType() {
    return type;
  }

  public void setType(CustomerContactType type) {
    this.type = type;
  }

  public MTOServiceItemDDFSIT timeMilitary1(String timeMilitary1) {
    this.timeMilitary1 = timeMilitary1;
    return this;
  }

   /**
   * Get timeMilitary1
   * @return timeMilitary1
  **/
  @ApiModelProperty(example = "0400Z", required = true, value = "")
  public String getTimeMilitary1() {
    return timeMilitary1;
  }

  public void setTimeMilitary1(String timeMilitary1) {
    this.timeMilitary1 = timeMilitary1;
  }

  public MTOServiceItemDDFSIT firstAvailableDeliveryDate1(LocalDate firstAvailableDeliveryDate1) {
    this.firstAvailableDeliveryDate1 = firstAvailableDeliveryDate1;
    return this;
  }

   /**
   * Get firstAvailableDeliveryDate1
   * @return firstAvailableDeliveryDate1
  **/
  @ApiModelProperty(example = "2020-01-20T00:00:00.000+0000", required = true, value = "")
  public LocalDate getFirstAvailableDeliveryDate1() {
    return firstAvailableDeliveryDate1;
  }

  public void setFirstAvailableDeliveryDate1(LocalDate firstAvailableDeliveryDate1) {
    this.firstAvailableDeliveryDate1 = firstAvailableDeliveryDate1;
  }

  public MTOServiceItemDDFSIT timeMilitary2(String timeMilitary2) {
    this.timeMilitary2 = timeMilitary2;
    return this;
  }

   /**
   * Get timeMilitary2
   * @return timeMilitary2
  **/
  @ApiModelProperty(example = "0400Z", required = true, value = "")
  public String getTimeMilitary2() {
    return timeMilitary2;
  }

  public void setTimeMilitary2(String timeMilitary2) {
    this.timeMilitary2 = timeMilitary2;
  }

  public MTOServiceItemDDFSIT firstAvailableDeliveryDate2(LocalDate firstAvailableDeliveryDate2) {
    this.firstAvailableDeliveryDate2 = firstAvailableDeliveryDate2;
    return this;
  }

   /**
   * Get firstAvailableDeliveryDate2
   * @return firstAvailableDeliveryDate2
  **/
  @ApiModelProperty(example = "2020-01-20T00:00:00.000+0000", required = true, value = "")
  public LocalDate getFirstAvailableDeliveryDate2() {
    return firstAvailableDeliveryDate2;
  }

  public void setFirstAvailableDeliveryDate2(LocalDate firstAvailableDeliveryDate2) {
    this.firstAvailableDeliveryDate2 = firstAvailableDeliveryDate2;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MTOServiceItemDDFSIT mtOServiceItemDDFSIT = (MTOServiceItemDDFSIT) o;
    return Objects.equals(this.reServiceCode, mtOServiceItemDDFSIT.reServiceCode) &&
        Objects.equals(this.type, mtOServiceItemDDFSIT.type) &&
        Objects.equals(this.timeMilitary1, mtOServiceItemDDFSIT.timeMilitary1) &&
        Objects.equals(this.firstAvailableDeliveryDate1, mtOServiceItemDDFSIT.firstAvailableDeliveryDate1) &&
        Objects.equals(this.timeMilitary2, mtOServiceItemDDFSIT.timeMilitary2) &&
        Objects.equals(this.firstAvailableDeliveryDate2, mtOServiceItemDDFSIT.firstAvailableDeliveryDate2) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reServiceCode, type, timeMilitary1, firstAvailableDeliveryDate1, timeMilitary2, firstAvailableDeliveryDate2, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MTOServiceItemDDFSIT {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    reServiceCode: ").append(toIndentedString(reServiceCode)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    timeMilitary1: ").append(toIndentedString(timeMilitary1)).append("\n");
    sb.append("    firstAvailableDeliveryDate1: ").append(toIndentedString(firstAvailableDeliveryDate1)).append("\n");
    sb.append("    timeMilitary2: ").append(toIndentedString(timeMilitary2)).append("\n");
    sb.append("    firstAvailableDeliveryDate2: ").append(toIndentedString(firstAvailableDeliveryDate2)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

