/*
 * Milmove Prime API
 * The Prime API is a RESTful API that enables the Prime contractor to request information about upcoming moves, update the details and status of those moves, and make payment requests. It uses Mutual TLS for authentication procedures.  All endpoints are located at `primelocal/prime/v1/`. 
 *
 * OpenAPI spec version: 0.0.1
 * Contact: dp3@truss.works
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.MTOServiceItem;
import io.swagger.client.model.MTOServiceItemModelType;
import io.swagger.client.model.MTOServiceItemStatus;
import io.swagger.client.model.ReServiceCode;
import java.io.IOException;
import java.util.UUID;

/**
 * Describes a domestic origin 1st day SIT service item subtype of a MTOServiceItem.
 */
@ApiModel(description = "Describes a domestic origin 1st day SIT service item subtype of a MTOServiceItem.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-14T14:53:44.624-07:00")
public class MTOServiceItemDOFSIT extends MTOServiceItem {
  @SerializedName("reServiceCode")
  private ReServiceCode reServiceCode = null;

  @SerializedName("reason")
  private String reason = null;

  @SerializedName("pickupPostalCode")
  private String pickupPostalCode = null;

  public MTOServiceItemDOFSIT reServiceCode(ReServiceCode reServiceCode) {
    this.reServiceCode = reServiceCode;
    return this;
  }

   /**
   * Get reServiceCode
   * @return reServiceCode
  **/
  @ApiModelProperty(value = "")
  public ReServiceCode getReServiceCode() {
    return reServiceCode;
  }

  public void setReServiceCode(ReServiceCode reServiceCode) {
    this.reServiceCode = reServiceCode;
  }

  public MTOServiceItemDOFSIT reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * Get reason
   * @return reason
  **/
  @ApiModelProperty(example = "Storage items need to be picked up", required = true, value = "")
  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }

  public MTOServiceItemDOFSIT pickupPostalCode(String pickupPostalCode) {
    this.pickupPostalCode = pickupPostalCode;
    return this;
  }

   /**
   * Get pickupPostalCode
   * @return pickupPostalCode
  **/
  @ApiModelProperty(example = "90210", required = true, value = "")
  public String getPickupPostalCode() {
    return pickupPostalCode;
  }

  public void setPickupPostalCode(String pickupPostalCode) {
    this.pickupPostalCode = pickupPostalCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MTOServiceItemDOFSIT mtOServiceItemDOFSIT = (MTOServiceItemDOFSIT) o;
    return Objects.equals(this.reServiceCode, mtOServiceItemDOFSIT.reServiceCode) &&
        Objects.equals(this.reason, mtOServiceItemDOFSIT.reason) &&
        Objects.equals(this.pickupPostalCode, mtOServiceItemDOFSIT.pickupPostalCode) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reServiceCode, reason, pickupPostalCode, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MTOServiceItemDOFSIT {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    reServiceCode: ").append(toIndentedString(reServiceCode)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    pickupPostalCode: ").append(toIndentedString(pickupPostalCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

