/*
 * move.mil API
 * The Prime API for move.mil
 *
 * OpenAPI spec version: 0.0.1
 * Contact: dp3@truss.works
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Upload;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ProofOfServiceDocs
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-06T14:55:33.605Z")
public class ProofOfServiceDocs {
  @SerializedName("uploads")
  private List<Upload> uploads = null;

  public ProofOfServiceDocs uploads(List<Upload> uploads) {
    this.uploads = uploads;
    return this;
  }

  public ProofOfServiceDocs addUploadsItem(Upload uploadsItem) {
    if (this.uploads == null) {
      this.uploads = new ArrayList<Upload>();
    }
    this.uploads.add(uploadsItem);
    return this;
  }

   /**
   * Get uploads
   * @return uploads
  **/
  @ApiModelProperty(value = "")
  public List<Upload> getUploads() {
    return uploads;
  }

  public void setUploads(List<Upload> uploads) {
    this.uploads = uploads;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProofOfServiceDocs proofOfServiceDocs = (ProofOfServiceDocs) o;
    return Objects.equals(this.uploads, proofOfServiceDocs.uploads);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uploads);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProofOfServiceDocs {\n");
    
    sb.append("    uploads: ").append(toIndentedString(uploads)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

