=begin
#move.mil API

#The Prime API for move.mil

OpenAPI spec version: 0.0.1
Contact: dp3@truss.works
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::PaymentRequestStatus
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PaymentRequestStatus' do
  before do
    # run before each test
    @instance = SwaggerClient::PaymentRequestStatus.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PaymentRequestStatus' do
    it 'should create an instance of PaymentRequestStatus' do
      expect(@instance).to be_instance_of(SwaggerClient::PaymentRequestStatus)
    end
  end
end
