=begin
#move.mil API

#The Prime API for move.mil

OpenAPI spec version: 0.0.1
Contact: dp3@truss.works
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::UpdatePaymentRequestStatus
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UpdatePaymentRequestStatus' do
  before do
    # run before each test
    @instance = SwaggerClient::UpdatePaymentRequestStatus.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UpdatePaymentRequestStatus' do
    it 'should create an instance of UpdatePaymentRequestStatus' do
      expect(@instance).to be_instance_of(SwaggerClient::UpdatePaymentRequestStatus)
    end
  end
  describe 'test attribute "rejection_reason"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "status"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "e_tag"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
