/*
 * Milmove Prime API
 * The Prime API is a RESTful API that enables the Prime contractor to request information about upcoming moves, update the details and status of those moves, and make payment requests. It uses Mutual TLS for authentication procedures.  All endpoints are located at `primelocal/prime/v1/`. 
 *
 * OpenAPI spec version: 0.0.1
 * Contact: dp3@truss.works
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Body;
import io.swagger.client.model.Error;
import io.swagger.client.model.MoveTaskOrder;
import io.swagger.client.model.MoveTaskOrders;
import io.swagger.client.model.ValidationError;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MoveTaskOrderApi
 */
@Ignore
public class MoveTaskOrderApiTest {

    private final MoveTaskOrderApi api = new MoveTaskOrderApi();

    
    /**
     * fetchMTOUpdates
     *
     * Gets all move task orders where &#x60;isAvailableToPrime&#x60; is TRUE. This prevents viewing any move task orders that have not been made available to the Prime. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchMTOUpdatesTest() throws ApiException {
        Integer since = null;
        MoveTaskOrders response = api.fetchMTOUpdates(since);

        // TODO: test validations
    }
    
    /**
     * updateMTOPostCounselingInformation
     *
     * Updates move task order after the counseling stage. Allows update of fields ppmType and ppmEstimatedWeight.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateMTOPostCounselingInformationTest() throws ApiException {
        String moveTaskOrderID = null;
        Body body = null;
        String ifMatch = null;
        MoveTaskOrder response = api.updateMTOPostCounselingInformation(moveTaskOrderID, body, ifMatch);

        // TODO: test validations
    }
    
}
