/*
 * move.mil API
 * The Prime API for move.mil
 *
 * OpenAPI spec version: 0.0.1
 * Contact: dp3@truss.works
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Error;
import io.swagger.client.model.MTOServiceItem;
import io.swagger.client.model.ResponsesPermissionDenied;
import java.util.UUID;
import io.swagger.client.model.ValidationError;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MtoServiceItemApi
 */
@Ignore
public class MtoServiceItemApiTest {

    private final MtoServiceItemApi api = new MtoServiceItemApi();

    
    /**
     * Creates MTO service items that is added to a Move Task Order and MTO Shipment
     *
     * Creates a new instance of mtoServiceItem, which come from the list of services that can be provided. Upon creation these items are associated with a Move Task Order and an MTO Shipment. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createMTOServiceItemTest() throws ApiException {
        UUID moveTaskOrderID = null;
        UUID mtoShipmentID = null;
        MTOServiceItem body = null;
        MTOServiceItem response = api.createMTOServiceItem(moveTaskOrderID, mtoShipmentID, body);

        // TODO: test validations
    }
    
}
