/*
 * move.mil API
 * The Prime API for move.mil
 *
 * OpenAPI spec version: 0.0.1
 * Contact: dp3@truss.works
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Error;
import io.swagger.client.model.MTOShipment;
import io.swagger.client.model.ResponsesPermissionDenied;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MtoShipmentApi
 */
@Ignore
public class MtoShipmentApiTest {

    private final MtoShipmentApi api = new MtoShipmentApi();

    
    /**
     * Updates MTO shipment
     *
     * Updates MTO shipment.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateMTOShipmentTest() throws ApiException {
        UUID moveTaskOrderID = null;
        UUID mtoShipmentID = null;
        MTOShipment body = null;
        String ifMatch = null;
        MTOShipment response = api.updateMTOShipment(moveTaskOrderID, mtoShipmentID, body, ifMatch);

        // TODO: test validations
    }
    
}
