/*
 * move.mil API
 * The Prime API for move.mil
 *
 * OpenAPI spec version: 0.0.1
 * Contact: dp3@truss.works
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Error;
import java.io.File;
import io.swagger.client.model.ResponsesPermissionDenied;
import io.swagger.client.model.Upload;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UploadsApi
 */
@Ignore
public class UploadsApiTest {

    private final UploadsApi api = new UploadsApi();

    
    /**
     * Create a new upload for a payment request
     *
     * Uploads represent a single digital file, such as a JPEG, PNG, or PDF.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createUploadTest() throws ApiException {
        String paymentRequestID = null;
        File file = null;
        Upload response = api.createUpload(paymentRequestID, file);

        // TODO: test validations
    }
    
}
