=begin
#move.mil API

#The Prime API for move.mil

OpenAPI spec version: 0.0.1
Contact: dp3@truss.works
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::MtoServiceItemApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MtoServiceItemApi' do
  before do
    # run before each test
    @instance = SwaggerClient::MtoServiceItemApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MtoServiceItemApi' do
    it 'should create an instance of MtoServiceItemApi' do
      expect(@instance).to be_instance_of(SwaggerClient::MtoServiceItemApi)
    end
  end

  # unit tests for create_mto_service_item
  # Creates MTO service items that is added to a Move Task Order and MTO Shipment
  # Creates a new instance of mtoServiceItem, which come from the list of services that can be provided. Upon creation these items are associated with a Move Task Order and an MTO Shipment. 
  # @param move_task_order_id UUID of Move Task Order to use.
  # @param mto_shipment_id UUID of MTO Shipment to use.
  # @param [Hash] opts the optional parameters
  # @option opts [MTOServiceItem] :body 
  # @return [MTOServiceItem]
  describe 'create_mto_service_item test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
