=begin
#move.mil API

#The Prime API for move.mil

OpenAPI spec version: 0.0.1
Contact: dp3@truss.works
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::MtoShipmentApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MtoShipmentApi' do
  before do
    # run before each test
    @instance = SwaggerClient::MtoShipmentApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MtoShipmentApi' do
    it 'should create an instance of MtoShipmentApi' do
      expect(@instance).to be_instance_of(SwaggerClient::MtoShipmentApi)
    end
  end

  # unit tests for update_mto_shipment
  # Updates MTO shipment
  # Updates MTO shipment.
  # @param move_task_order_id UUID of the move task order being used.
  # @param mto_shipment_id UUID of the move task order shipment being updated.
  # @param body 
  # @param if_match Optimistic locking is implemented via the &#x60;If-Match&#x60; header. If the ETag header does not match the value of the resource on the server, the server rejects the change with a &#x60;412 Precondition Failed&#x60; error. 
  # @param [Hash] opts the optional parameters
  # @return [MTOShipment]
  describe 'update_mto_shipment test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
