=begin
#move.mil API

#The Prime API for move.mil

OpenAPI spec version: 0.0.1
Contact: dp3@truss.works
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'date'

module SwaggerClient
  class MTOServiceItemModelType
    
    MTO_SERVICE_ITEM_BASIC = 'MTOServiceItemBasic'.freeze
    MTO_SERVICE_ITEM_DOFSIT = 'MTOServiceItemDOFSIT'.freeze
    MTO_SERVICE_ITEM_DDFSIT = 'MTOServiceItemDDFSIT'.freeze
    MTO_SERVICE_ITEM_SHUTTLE = 'MTOServiceItemShuttle'.freeze
    MTO_SERVICE_ITEM_DOMESTIC_CRATING = 'MTOServiceItemDomesticCrating'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = MTOServiceItemModelType.constants.select { |c| MTOServiceItemModelType::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #MTOServiceItemModelType" if constantValues.empty?
      value
    end
  end
end
