=begin
#move.mil API

#The Prime API for move.mil

OpenAPI spec version: 0.0.1
Contact: dp3@truss.works
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'date'

module SwaggerClient
  class ReServiceCode
    
    CS = 'CS'.freeze
    DBHF = 'DBHF'.freeze
    DBTF = 'DBTF'.freeze
    DCRT = 'DCRT'.freeze
    DCRTSA = 'DCRTSA'.freeze
    DDASIT = 'DDASIT'.freeze
    DDDSIT = 'DDDSIT'.freeze
    DDFSIT = 'DDFSIT'.freeze
    DDP = 'DDP'.freeze
    DDSHUT = 'DDSHUT'.freeze
    DLH = 'DLH'.freeze
    DMHF = 'DMHF'.freeze
    DNPKF = 'DNPKF'.freeze
    DOASIT = 'DOASIT'.freeze
    DOFSIT = 'DOFSIT'.freeze
    DOP = 'DOP'.freeze
    DOPSIT = 'DOPSIT'.freeze
    DOSHUT = 'DOSHUT'.freeze
    DPK = 'DPK'.freeze
    DSH = 'DSH'.freeze
    DUCRT = 'DUCRT'.freeze
    DUPK = 'DUPK'.freeze
    FSC = 'FSC'.freeze
    IBHF = 'IBHF'.freeze
    IBTF = 'IBTF'.freeze
    ICOLH = 'ICOLH'.freeze
    ICOUB = 'ICOUB'.freeze
    ICRT = 'ICRT'.freeze
    ICRTSA = 'ICRTSA'.freeze
    IDASIT = 'IDASIT'.freeze
    IDDSIT = 'IDDSIT'.freeze
    IDFSIT = 'IDFSIT'.freeze
    IDSHUT = 'IDSHUT'.freeze
    IHPK = 'IHPK'.freeze
    IHUPK = 'IHUPK'.freeze
    INPKF = 'INPKF'.freeze
    IOASIT = 'IOASIT'.freeze
    IOCLH = 'IOCLH'.freeze
    IOCUB = 'IOCUB'.freeze
    IOFSIT = 'IOFSIT'.freeze
    IOOLH = 'IOOLH'.freeze
    IOOUB = 'IOOUB'.freeze
    IOPSIT = 'IOPSIT'.freeze
    IOSHUT = 'IOSHUT'.freeze
    IUBPK = 'IUBPK'.freeze
    IUBUPK = 'IUBUPK'.freeze
    IUCRT = 'IUCRT'.freeze
    MS = 'MS'.freeze
    NSTH = 'NSTH'.freeze
    NSTUB = 'NSTUB'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = ReServiceCode.constants.select { |c| ReServiceCode::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #ReServiceCode" if constantValues.empty?
      value
    end
  end
end
