=begin
#move.mil Prime API

#The API for move.mil Prime actions.

OpenAPI spec version: 0.1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.8

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/client_error'
require 'swagger_client/models/customer'
require 'swagger_client/models/entitlements'
require 'swagger_client/models/move_task_order'
require 'swagger_client/models/move_task_orders'
require 'swagger_client/models/options'
require 'swagger_client/models/service_item'
require 'swagger_client/models/validation_error'

# APIs
require 'swagger_client/api/move_task_order_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
