=begin
#move.mil Prime API

#The API for move.mil Prime actions.

OpenAPI spec version: 0.1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.8

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::ServiceItem
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ServiceItem' do
  before do
    # run before each test
    @instance = SwaggerClient::ServiceItem.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ServiceItem' do
    it 'should create an instance of ServiceItem' do
      expect(@instance).to be_instance_of(SwaggerClient::ServiceItem)
    end
  end
  describe 'test attribute "requestor"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
